name: "Build & Release"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - develop

jobs:
  build-android:
    name: Build & Release Android
    runs-on: windows-latest

    env:
      FLUTTER_VERSION: 3.13.7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/release/*.apk

  build-ios:
    name: Build & Release iOS
    runs-on: macos-latest
    needs: build-android

    env:
      FLUTTER_VERSION: 3.13.7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-ipa
          path: build/ios/iphoneos/app.ipa

  release:
    name: Release artifacts
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: 
            android-apk
            ios-ipa

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ${{ steps.download-artifacts.outputs.artifacts }}/android-apk/*.apk,
            ${{ steps.download-artifacts.outputs.artifacts }}/ios-ipa/*.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
